Allow changing of battle backgrounds via json
Tuxemon/Tuxemon pull request #1068
Opened 2021-11-18 21:41 UTC by ultidonki

In the wiki, we have about 20 cool battle BG images, already sized to the game's resolution. 
But, for some reason we haven't put any of them into the game yet.

This PR adds:
* 1 image from the wiki, plus license info in CREDITS.md
* The ability to change the background, in combat_animations.py and combat.py
* * (it falls back to the default if the background isn't specified, similar to how island_front and island_back work)
* An example of changing the grass.json environment to a new BG, using battle_background property in 'graphics' dict

Here's how it looks in the grass environment now: (all other environments look the same as they did previously)
![new_battle_bgs](https://user-images.githubusercontent.com/89098769/142501125-c4f28667-4a69-4ce0-b479-c7b07f6467f1.png)

2021-11-18 21:45 UTC, vnmabus commented
This is very cool! I think in the future we should allow map areas to have different backgrounds, though.

2021-11-18 21:50 UTC, ultidonki commented
Thanks! But I think environments can still be used for different maps? For example, you could have a my-map1.json environment, that changes the background, and battle music, just for my-map? Or are environments intended to be something more general than map stuff?

2021-11-18 21:59 UTC, vnmabus commented
Mmmm, I think you are right. It seems the environment can be changed changing a player variable, so it would even be possible to have several ones in the same map.

2021-11-18 22:13 UTC, ultidonki commented
I'm glad environments work the way I expected, thanks for checking! Changing the environment inside a map is actually something I hadn't thought of... I could probably use that for a boss battle in my mod, if this gets accepted. Thanks for the idea! ;)

2021-11-19 10:13 UTC, bitcraft requested changes
this is a great addition!  thank you for this.  i have a couple comments on there, but overall this is great.

2021-11-19 10:13 UTC, bitcraft commented on mods/tuxemon/db/environment/grass.json
> +    "background":"Background_240px.png"
we've had issues in the past with mixed case filenames.  some OS will allow mixing them and others won't and it has created issues with loading images.  please rename the file to be all lower case.

2021-11-19 10:13 UTC, bitcraft commented on tuxemon/states/combat/combat_animations.py
> +        if "background" in graphics and graphics["background"] > "":
can we change this to:
```python
if "background" in graphics and graphics["background"]:
```

2021-11-19 11:21 UTC, vnmabus commented on tuxemon/states/combat/combat_animations.py
> +        if "background" in graphics and graphics["background"] > "":
Even better:
```suggestion
        background = graphics.get("background")
        if background:
```

2021-11-19 22:47 UTC, ultidonki commented
I've made those 2 changes - and also took the opportunity to rename the file to be more maintainable in the future, ie. forest_background.png, to make it more obvious what it is without having to open it. Thanks both!

2021-11-21 12:34 UTC, bitcraft approved these changes
great feature, thank you!

2021-11-21 12:34 UTC, merged