Add print action. Closes #1100
Tuxemon/Tuxemon pull request #1103
Opened 2022-01-09 12:29 UTC by ultidonki

This adds a print action, callable from map events. See #1100 for details

The following map tests printing a bunch of variables, some that exist, some that don't:
[test_print_action.zip](https://github.com/Tuxemon/Tuxemon/files/7835012/test_print_action.zip)

2022-01-10 16:48 UTC, bitcraft requested changes
thank you for adding the documentation to the docs.  please see the comments.

2022-01-10 16:48 UTC, bitcraft commented on tuxemon/event/actions/print.py
> +
Should be decorated by `@final`
```python
from typing import final

@final
class Foo...
```

2022-01-10 16:48 UTC, bitcraft commented on tuxemon/event/actions/print.py
> +    Print the current value of a game variable.
Please change to "Print the current value of a game variable to the console".  Some people might think it is printed to the game screen.

2022-01-10 16:48 UTC, bitcraft commented on tuxemon/event/actions/print.py
> +        if variable and variable > "":
Please don't use the `>` operator to compare strings.  `if variable` is sufficient to check for empty strings.

2022-01-10 16:48 UTC, bitcraft commented on tuxemon/event/actions/print.py
> +    If no variables are specified, print out values of all game variables.
please change "variables" to "variable", since only one variable is supported.

2022-02-01 19:58 UTC, ultidonki commented
Thank you - I've made the changes requested in each comment now!

2022-02-06 18:50 UTC, bitcraft approved these changes
lgtm

2022-02-06 18:50 UTC, merged