Things
Tuxemon/Tuxemon pull request #1131
Opened 2022-03-09 23:30 UTC by SandytheLizard

1. Redid about 30% of the moves
2.Added a cli command called random_fight. this generates a random 6v6 battle. This command will crash if you have tuxemon in your party upon execution or if it picks a tuxemon without a valid shape.

3. Made it so stats revert after a battle.

2022-03-10 13:41 UTC, bitcraft requested changes
please see the comments

2022-03-10 13:41 UTC, bitcraft commented on mods/tuxemon/l18n/en_US/LC_MESSAGES/base.po
> -msgstr "{user}'s speed was halved."
please remove the space that was added here and in the next line

2022-03-10 13:41 UTC, bitcraft commented on mods/tuxemon/l18n/en_US/LC_MESSAGES/base.po
> -msgstr "{user}'s attack damage types rose."
please remove the space between the user/target and `'s`

2022-03-10 13:41 UTC, bitcraft commented on tuxemon/event/actions/random_battle.py
> +class randomfight(EventAction[AddMonsterActionParameters]):
* class names must be CamelCase and begine with a capital letter
* class name in this file should match the name of the file.  ie: RandomBattle

2022-03-10 13:41 UTC, bitcraft commented on tuxemon/event/actions/random_battle.py
> +
please run `black -l 79 tuxemon/event/actions/random_battle` to fix the formatting of this file

2022-03-10 13:41 UTC, bitcraft commented on tuxemon/event/actions/random_battle.py
> +    a
Please be more descriptive.  and include what this does, specifically, and why it is difference than a "random encounter"

2022-03-10 13:41 UTC, bitcraft commented on tuxemon/event/actions/random_battle.py
> +    name = "random_fight"
please change fight to battle

2022-03-10 13:41 UTC, bitcraft commented on tuxemon/event/actions/random_battle.py
> +    param_class = AddMonsterActionParameters
correct this

2022-03-10 13:41 UTC, bitcraft commented on tuxemon/event/actions/random_battle.py
> +class AddMonsterActionParameters(NamedTuple):
None of this is correct.  are parameters used?  if so, you need to rename this class and also change the values

2022-03-10 13:41 UTC, bitcraft commented on tuxemon/event/actions/random_battle.py
> +        file_path = 'tuxemon/db/monster/'
it looks like you are trying to get all the available monster slugs.  if that is the case, there is no need to search the json from disk. you can get all the slugs for ``mon_slug_list` like this
```python
mon_slug_list = list(db.database["monster"].keys())
```
please remove all the code which reads the json and replace it with the code above.

2022-03-10 13:41 UTC, bitcraft commented on tuxemon/event/actions/random_battle.py
> +        if slug in world.npcs:
this creates a problem that this action will silently fail if the npc already exists.  please add an error logging statement that informs the player/developer that the battle cannot start.  or consider making a new NPC json that is only used for debugging battles like this one.

2022-03-10 13:41 UTC, bitcraft commented on tuxemon/event/actions/random_battle.py
> +        if sprite:
please remove all of this

2022-03-10 13:41 UTC, bitcraft commented on tuxemon/event/actions/random_battle.py
> +        npc.load_party()
is this required?  you are just replacing the monsters in the next few lines

2022-03-10 13:41 UTC, bitcraft commented on tuxemon/event/actions/random_battle.py
> +        # Don't start a battle if we don't even have monsters in our party yet.
move this check to the top, before all the monster loading happens

2022-03-10 13:41 UTC, bitcraft commented on tuxemon/event/actions/random_battle.py
> +        world = self.session.client.get_state_by_name(WorldState)
this is a duplicate

2022-03-10 13:41 UTC, bitcraft commented on tuxemon/event/actions/random_battle.py
> +            combat_type="player",
this is a `trainer` battle

2022-05-02 21:06 UTC, bitcraft commented on mods/tuxemon/l18n/en_US/LC_MESSAGES/base.po
> +msgstr "{user's {stat} increased."
should be `{user}`

2022-07-19 06:38 UTC, kerizane requested changes

2022-07-19 06:38 UTC, kerizane commented on mods/tuxemon/db/technique/avalanche.json
> +  "statspeedd": {
Typo?

2023-04-24 12:09 UTC, closed without merging