add ci file for flatpak
Tuxemon/Tuxemon pull request #1179
Opened 2022-05-12 08:32 UTC by Murmele

Add automatic build of the flatpak package

2022-07-19 06:01 UTC, kerizane commented
Can you take a look at the failing build?

2022-07-19 06:01 UTC, kerizane requested changes
Fix the build.

2022-07-19 20:44 UTC, kerizane commented
Well, you can validate the yaml using a tool like this: http://www.yamllint.com/

2022-07-19 20:45 UTC, kerizane requested changes

2022-07-19 20:45 UTC, kerizane commented on .github/workflows/build_flatpak.yml
> +    - name: Checkout development branch (TODO: remove this once a new version of tuxemon is released)
It doesn't like the colon after "TODO", change it to something else, e.g. "TODO - "

2022-07-20 05:52 UTC, Murmele commented
On hold for now as long as the package is not published on flathub. Hopefully next days

2022-07-20 16:54 UTC, kerizane approved these changes, later dismissed

2022-08-02 07:39 UTC, Murmele commented
@kerizane it is building now. You can test the flatpak from the build artifacts: https://github.com/Tuxemon/Tuxemon/actions/runs/2780343304

2022-08-02 19:17 UTC, kerizane approved these changes

2022-08-02 19:17 UTC, merged