JSONs gender
Tuxemon/Tuxemon pull request #1354
Opened 2022-09-24 17:52 UTC by JaskRendix

Genders for npcs and monsters.
This PR is for creating the data structure JSONs.

My question is: do we need to use the same field "gender" for both? Is it ok?

2022-09-25 10:22 UTC, kerizane commented
Add "gender" to pydantic validation for NPCs.
Can we add it to npc.monster,  but not to monster?
We should pick appropriate genders for the npc monsters, but can be done in a future ticket if you prefer.
The monsters JSON should include "possible_genders", this should be a list of strings: male, female, neuter.
When you create monster you should pick one of the possoble_genders at random. Most monsters can be male or female, some can only be neuter or only male or only female.

2022-09-25 11:44 UTC, JaskRendix commented
> Add "gender" to pydantic validation for NPCs.

Done.

> Can we add the h validation to npc.monster, but not to monster?

PartyMemberModel?

>  Pick more appropriate genders for the npc monsters.

Work in progress

> The monsters JSON should include "possible_genders", this should be a list of strings: male, female, neuter.

I guess you're still referring the the PartyMemberModel?

2022-09-25 11:48 UTC, JaskRendix commented
It would become like this?
```
{
  "slug": "spyder_citypark_edith",
  "gender": "female",
  [...]
  "monsters": [
    {
      "name": "Squabbit",
      [...]
      "possible_genders": "neutral"
    }
  ],
  "combat_front": "picnicker.png",
  "combat_back": "red_back.png"
}
```

2022-09-25 12:18 UTC, kerizane commented
Gender should be on npc and PartyMemberModel, possible_genders should be on monster.

2022-09-25 12:20 UTC, kerizane commented
```
{
  "slug": "spyder_citypark_edith",
  "gender": "female",
  [...]
  "monsters": [
    {
      "name": "Squabbit",
      [...]
      "gender": "neutral"
    }
  ],
  "combat_front": "picnicker.png",
  "combat_back": "red_back.png"
}
```

2022-09-25 13:31 UTC, JaskRendix commented
Ok, it was a bunch of stuff, but another step has been done. Let me know if you like the enum idea.

2022-09-25 13:33 UTC, JaskRendix commented
Ah yeah, you said neuter, not neutral, I'll update after you check.

2022-09-25 13:38 UTC, kerizane commented on tuxemon/db.py
> +    possible_gender: GenderType = Field(..., description="The gender of the monster")
```
possible_genders: Sequence[GenderType]
```

2022-09-25 13:38 UTC, kerizane commented on tuxemon/db.py
> +    gender: str = Field(..., description="Gender of the monster")
gender: GenderType

2022-09-25 13:38 UTC, kerizane commented on tuxemon/db.py
> +    gender: str = Field(..., description="Gender of the NPC")
gender: GenderType

2022-09-25 13:39 UTC, kerizane commented on tuxemon/monster.py
> +        self.possible_gender = self.shape = GenderType.neutral
??

2022-09-25 13:41 UTC, JaskRendix commented on tuxemon/monster.py
> +        self.possible_gender = self.shape = GenderType.neutral
sorry, confusion, I'll correct

2022-09-25 14:04 UTC, JaskRendix commented
I'm going to fix neutral -> neuter.

2022-09-25 14:09 UTC, JaskRendix commented
Fixed neutral -> neuter, I guess we need to add **possible_gender** to the monster jsons too?

2022-09-25 14:31 UTC, kerizane commented
Yeah, this will be a bit of work. To do this properly you will need to go through every monster and define what genders they can be.

Most will be ["male", "female"].
There are some with the male/female symbol in their name, so these will be ["male"] or ["female"].
And some might need to be ["neuter"].

If this will require too much work we can split it off into another ticket.

2022-09-25 16:30 UTC, JaskRendix commented
No problem, I have already done the list of exceptions, because of the npc_monsters.
 
- only female: nudiflot_female, nudimind (evolution of nudiflot_female), viviteel (vivipere evolves into viviteel if female)
- only male: nudiflot_male, nudikill nudimind (evolution of nudiflot_male)
- only neuter: botbot, av8r, picc, mrmoswitch, k9, mk01_alpha, mk01_beta, birb-robo, chrome-robo, dark_robo, xeon, xeon_2, r0ck1tt3n, l3gk0, f7u1t3ra, d0llf1n, pythwire, ouroboutlet, sockeserp

Curiosity: is there a male evolution for vivipere? Yeah, but it's not added at the moment.

Think about this: we have 185 monster, the NPCs use only 106!

2022-09-27 07:54 UTC, kerizane requested changes

2022-09-27 07:54 UTC, kerizane commented on tuxemon/db.py
> +    possible_gender: Sequence[GenderType] = Field(..., description="The gender of the monster")
I still think this should be plural: possible_genders also the description 

`description="Valid genders for the monster"`

2022-09-27 07:55 UTC, kerizane commented
Neuter not fixed eithin

2022-09-27 09:07 UTC, JaskRendix commented
Done as requested, renaming included.

2022-09-27 12:02 UTC, kerizane commented on tuxemon/monster.py
> +        self.possible_genders = GenderType
```
self.possible_genders: List[GenderType] = []
```

2022-09-27 12:07 UTC, kerizane approved these changes

2022-09-27 13:10 UTC, kerizane commented
Sorry, the following comment was meant to go on this PR:

"Have you tested combat against a wild monster and against an NPC?

If you run make validate from the base of the repo are there any errors?"

2022-09-27 13:12 UTC, kerizane commented
If `make validate` doesn't complain, then it has passed.

2022-09-27 13:15 UTC, JaskRendix commented
No errors. Make validate as before:
```
PYTHONPATH=. python scripts/schema.py --validate
pygame 2.1.2 (SDL 2.0.16, Python 3.10.6)
Hello from the pygame community. https://www.pygame.org/contribute.html
```

2022-09-27 13:31 UTC, merged

2022-09-28 11:37 UTC, Sanglorian commented
> No problem, I have already done the list of exceptions, because of the npc_monsters.

Thanks for this list! I've added "Sex" as a variable in the wiki for monsters, and done it for all monsters other than the glitch Tuxemon - which I think are fine to have sexes.