fix typehints
Tuxemon/Tuxemon pull request #1711
Opened 2023-03-29 14:49 UTC by JaskRendix

progressing #1211 updated mypy, always --strict

2023-03-30 07:41 UTC, kerizane commented on tuxemon/map.py
> +        assert self.renderer
Indentation looks wrong

2023-03-30 07:43 UTC, kerizane commented on tuxemon/map_loader.py
> +            if isinstance(key, str):
Let's do

```
if not is instance(key, str):
    continue
```

2023-03-30 07:44 UTC, kerizane commented on tuxemon/map_loader.py
> +            if isinstance(key, str):
To avoid increasing the indentation

2023-03-30 07:45 UTC, kerizane requested changes
Comment

2023-03-30 08:37 UTC, JaskRendix commented on tuxemon/map_loader.py
> +            if isinstance(key, str):
it makes sense

2023-04-01 11:42 UTC, kerizane approved these changes

2023-04-01 11:43 UTC, merged