swimming (Spyder)
Tuxemon/Tuxemon pull request #1787
Opened 2023-04-26 10:59 UTC by JaskRendix

PR addresses swimming, precisely the change of sprite from heroine/adventurer to swimmer.
- updates the action **set_player_template** by introducing the option **default**, default will restore the original sprite (the sprite the player chooses at the beginning, so if male -> adventurer, if female -> heroine);
- creates the condition **has_sprite** to check if the player has a specific sprite of not;

@sanglorian I thought about it (considering the sea route map too) and I realized that we cannot offer swimming anywhere. What I mean to say is... we need to establish specific zone to swim.

Look here:
I redraw the piece of coast to simplify the situation. Because there will be an event called walk (on land) and an event called swim (on water), these two events will change the sprite from adventurer / heroine to swimmer.
![spyder_paper_town](https://user-images.githubusercontent.com/64643719/234554252-45e5e19e-5aed-4959-9478-6438056f932b.png)
![spyder_paper_town2](https://user-images.githubusercontent.com/64643719/234554219-bbcf6f7b-31bc-45c5-b6ae-676d3b1dccdb.png)

but the issue is here, Candy Town:
before
![spyder_candy_town](https://user-images.githubusercontent.com/64643719/234554882-c7b582a9-f557-48bf-ae2e-640284725403.png)
after
![spyder_candy_town2](https://user-images.githubusercontent.com/64643719/234554925-137e3a5e-dd70-48df-bb5e-f0df91a7bfca.png)
as you can see in the second image there are two places that will allow to swim (above) and bottom right.
This means that if someone comes from the ocean, he is going to stay swimmer while swimming on the river

this will simplify the introduction of fishing (eg made it possible not anywhere, but in specific points)

2023-04-26 13:01 UTC, Sanglorian commented
Thanks for this! 

I don't mind straightening out the coastlines to make the events simpler, but I'd rather not fence off the water if possible. Does it make it much more complicated to have events all along the coastline?

2023-04-26 13:23 UTC, JaskRendix commented
> Does it make it much more complicated to have events all along the coastline?

No, it doesn't. We can do it. What about the rivers? Do you want always accessible?

2023-04-26 13:48 UTC, Sanglorian commented
> > Does it make it much more complicated to have events all along the coastline?
> 
> No, it doesn't. We can do it. What about the rivers? Do you want always accessible?

Yes please! Thanks for this, I'm really excited to have this in place.

2023-04-26 14:02 UTC, JaskRendix commented
@Sanglorian updated the Candy Town map above with all the events (walk/swim)

2023-04-29 07:19 UTC, JaskRendix commented
@Sanglorian I got rid of the majority of stuff inside the PR, I'm going to try to implement the system you described in the other PR.

2023-04-29 09:36 UTC, JaskRendix commented
@Sanglorian I got rid of the majority of stuff inside the PR, I'm going to try to implement the system you described in the other PR.

If you can give me a message like "the fish has took the hook" and a message like "nothing" it would be great.

2023-04-29 12:17 UTC, Sanglorian commented
> @Sanglorian I got rid of the majority of stuff inside the PR, I'm going to try to implement the system you described in the other PR.
> 
> If you can give me a message like "nothing on the hook" (I'm not English native, I'm not accustomed with fishing expressions), eventually we can fix it in another PR.

Thanks heaps! How about, "The water ripples, but nothing bites."

2023-04-29 12:57 UTC, kerizane requested changes

2023-04-29 12:57 UTC, kerizane commented on tuxemon/item/effects/fishing.py
> +        levels = ["bas", "adv", "pro"]
Can we do:

basic, advanced, pro?

2023-04-29 12:57 UTC, kerizane commented on tuxemon/item/effects/fishing.py
> +class LearnMmEffectResult(ItemEffectResult):
Copypaste mistake?

2023-04-29 12:58 UTC, kerizane commented on tuxemon/item/effects/fishing.py
> +class LearnMmEffectResult(ItemEffectResult):
Tbh, I wouldn't bother subclassing. Just use ItemEffectResult

2023-04-29 12:59 UTC, JaskRendix commented on tuxemon/item/effects/fishing.py
> +class LearnMmEffectResult(ItemEffectResult):
Yeah, copypaste, thanks!

2023-04-29 13:00 UTC, JaskRendix commented on tuxemon/item/effects/fishing.py
> +        levels = ["bas", "adv", "pro"]
sure

2023-04-30 06:22 UTC, kerizane approved these changes

2023-04-30 06:23 UTC, merged