add techniques + technique effects
Tuxemon/Tuxemon pull request #1869
Opened 2023-05-24 13:56 UTC by JaskRendix

split from #1853 

PR:
adds **empty** technique (similar to **skip**), necessary to avoid issues since **skip** appears only if both techniques are without recharge;
adds **neutralize**;
adds **tinder** (gives status_burn, status_burn will be added in another PR);
adds **remove** technique effect (removes status/condition);
adds **reverse** technique effect (reverse **switch**);
renames **status_spyderbite** into **spyderbite** since it's not a status (avoid confusion next changes);

2023-05-24 21:32 UTC, Sanglorian commented
Great, thank you!

2023-05-25 08:09 UTC, kerizane submitted a review, later dismissed

2023-05-27 07:39 UTC, kerizane requested changes

2023-05-27 07:39 UTC, kerizane commented on mods/tuxemon/l18n/de_DE/LC_MESSAGES/base.po
> -msgid "status_spyderbite"
Can you fix this and all the others

2023-05-27 07:51 UTC, JaskRendix commented on mods/tuxemon/l18n/de_DE/LC_MESSAGES/base.po
> -msgid "status_spyderbite"
Done

2023-05-27 14:11 UTC, kerizane approved these changes

2023-05-27 14:11 UTC, merged