Update the portable Linux and Windows pypy builds
Tuxemon/Tuxemon pull request #2014
Opened 2023-10-07 14:08 UTC by NeonFlames

2023-10-07 16:45 UTC, JaskRendix approved these changes

2023-10-12 12:40 UTC, bitcraft requested changes
looks good, minor changes requested

2023-10-12 12:40 UTC, bitcraft commented on buildconfig/build_pypy_portable_linux.sh
> +apt install -y curl coreutils
please remove `-y`.  we should not make a habit of building as root

2023-10-12 12:40 UTC, bitcraft commented on buildconfig/build_pypy_portable_linux.sh
> +# Tested in a debian stable container
please include debian version

2023-10-12 12:40 UTC, bitcraft commented on buildconfig/build_pypy_portable_windows.sh
> +# Tested in a debian stable container
please include the version

2023-10-12 12:40 UTC, bitcraft commented on buildconfig/build_pypy_portable_windows.sh
> +apt install -y wine curl coreutils p7zip-full
please remove `-y`

2023-10-12 22:04 UTC, bitcraft approved these changes

2023-10-12 22:04 UTC, merged