bump pygame-ce to 2.3.2
Tuxemon/Tuxemon pull request #2086
Opened 2023-11-10 09:48 UTC by JaskRendix

PR proposes to bump pygame-ce, there are no issues, but there are a few new typehints

2023-11-10 16:10 UTC, Grimmys requested changes
Most of my comments are related to the over-use of `assert`.
To be honest, I don't like assert pattern outside of tests, it looks archaic for me and not suited to OOP but that's a personal preference.

I just feel like we should at least avoid putting assertions in places where the variable cannot be undefined, because it's adding extra complexity to the code for nothing (since the statements are useless).

2023-11-10 16:10 UTC, Grimmys commented on tuxemon/graphics.py
> +    assert sprite.image
I'm don't think this assert is useful.

If there is no image, then it means `filename` was invalid.
Looking at the implementation of `load_and_scale` method and inner calls, if `filename` doesn't exist, it should already  fail at this point because we are not making any null check.

2023-11-10 16:10 UTC, Grimmys commented on tuxemon/monster.py
> +                assert surface.image and flair_sprite.image
Again, I don't think this assert can ever fail.
`surface` and `flair_sprite` are in any case loaded using `graphics.load_sprite` or `graphics.load_animated_sprite` methods. These two methods should fail if the provided path is invalid.

2023-11-10 16:10 UTC, Grimmys commented on tuxemon/sprite.py
> +    def image(self) -> Union[Surface, None]:
Let's use `Optional[Surface]` instead

2023-11-10 16:10 UTC, Grimmys commented on tuxemon/states/combat/combat.py
> +            assert hud.image
This method is going to be called at every game iteration, do we really assume `hud.image` can be changed to null at any point?

If there is no external element which can modify the `hud.image`, then I would suggest to do this check at instance creation instead.

2023-11-10 16:10 UTC, Grimmys commented on tuxemon/states/combat/combat.py
> +            assert hud.image
Same as for `draw_hp_bars` method

2023-11-10 16:10 UTC, Grimmys commented on tuxemon/states/combat/combat_animations.py
> +        assert capdev.image
Again, if `capdev.image` is undefined it should already fail earlier (`graphics.load_sprite` would fail)

2023-11-10 16:10 UTC, Grimmys commented on tuxemon/states/combat/combat_animations.py
> +            assert hud.image
Same, `hud.image` has to be defined at this point.

2023-11-10 16:10 UTC, Grimmys commented on tuxemon/states/combat/combat_animations.py
> +            assert hud.image
Same.

2023-11-10 16:32 UTC, JaskRendix commented
@Grimmys let's simplify

2023-11-10 17:05 UTC, Grimmys approved these changes

2023-11-15 00:15 UTC, xirsoi approved these changes

2023-11-15 00:15 UTC, merged