update NuPhone (state)
Tuxemon/Tuxemon pull request #2112
Opened 2023-11-19 11:16 UTC by JaskRendix

PR:
- splits NuPhone into the components: contacts, map, banking and phone, it'll simply future operations;
- move some graphical values in menu.theme (default one);

2023-11-27 18:26 UTC, bitcraft requested changes
please make sure all the font size values are scaled to the screen

2023-11-27 18:26 UTC, bitcraft commented on tuxemon/states/pc_locker/__init__.py
> +        theme.title_font_size = 30
notice that `theme.title_font_size = round(0.025 * width)`.  width is based off screen size, which means that it is scaled to the pixel size of the window.  by setting `30` here, the fotn will only be the correct size at whatever resolution you are using now.  we support multiple resolutions, so this value should be scaled to the screen somehow.  you can use `width`, or prepare.SCALE so the font is always the right size.

2023-11-27 18:26 UTC, bitcraft commented on tuxemon/states/phone/phone.py
> +                label, action=partial(uninstall, item), font_size=15
font_size needs to be scaled.  same on line 105

2023-11-27 18:26 UTC, bitcraft commented on tuxemon/states/phone/phone.py
> +        theme.title_font_size = 30
scaled font size

2023-11-27 18:26 UTC, bitcraft commented on tuxemon/states/phone/phone_banking.py
> +            font_size=20,
scale font size, and line 46

2023-11-27 18:26 UTC, bitcraft commented on tuxemon/states/phone/phone_banking.py
> +            font_size=20,
more scaled font size, and line 137, 159

2023-11-27 22:07 UTC, bitcraft commented on tuxemon/states/phone/phone_map.py
> +class NuPhoneMap(PygameMenuState):
i think this is OK as just some experimental code, but because it is hardcoding the map names here, it can't really stay like this forever, since it means the codebase is tied to a specific thing.  i don't have a good solution right now, but i think something along the lines of a game variable which contains the maps would be used to generate this list.  if you don't have a solution, please put in a comment like the following
```
This is experimental code for the NuPhone Map.  Currently these map names are are hardcoded,
but in the future, we will need to use some other data source to get the map names so that this
code is not directly tied to any specific maps.
```

2023-11-27 22:07 UTC, bitcraft commented on tuxemon/states/phone/phone_map.py
> +            background_color=(232, 48, 48),
just curious, can this use the theme, or do we want to hardcode the colors/fonts?

2023-11-27 22:27 UTC, JaskRendix commented on tuxemon/states/phone/phone_map.py
> +class NuPhoneMap(PygameMenuState):
you're right, I'm going to purge the map, because it's experimental code (I implemented it, and it needs to be redone completely)

2023-11-27 22:35 UTC, JaskRendix commented on tuxemon/states/phone/phone_map.py
> +            background_color=(232, 48, 48),
we can use the theme, no use to hardcode

2023-11-28 14:38 UTC, bitcraft approved these changes

2023-11-28 14:38 UTC, merged