class EntityFacing
Tuxemon/Tuxemon pull request #2126
Opened 2023-11-29 09:03 UTC by JaskRendix

While working on #2121 I noticed:
`facing = "front", "back", "left", "right"`
out of curiosity I looked for all the reference and I got only 3, map.py itself as well as npc.py;
so I enlarged and I looked for all the references connected to "back" and "front" and I bumped into:
`Literal["front", "back", "left", "right"]`
I'm not against Literals, but if we have the same kind of literal in two different places, then we can centralize

2023-11-30 20:52 UTC, Grimmys requested changes
Good improvement idea 👍

2023-11-30 20:52 UTC, Grimmys commented on tuxemon/db.py
> +        for facing in list(EntityFacing):
I don't get the logic there.

You loop other the list of all the facing... And for each of them you assign the corresponding sprite path to the `sprite` variable.

But since `sprite` is not an array/list, you are just _**overriding**_ its value at every new iteration. At the end, you only have the last facing sprite path in the variable, what's the point of the loop then?

2023-11-30 20:52 UTC, Grimmys commented on tuxemon/db.py
> +        if sprite and has.file(sprite) or has.file(sprite_obj):
`sprite` should always be defined at this point, since it's something static (the last facing from the Enum).
No need to check it then.

2023-11-30 21:06 UTC, JaskRendix commented on tuxemon/db.py
> +        for facing in list(EntityFacing):
you're right, I can simplify it video a pointless loop and overriding, I just need to check the 4 parameters and nothing more

2023-12-03 01:35 UTC, xirsoi approved these changes

2023-12-03 01:35 UTC, merged