get monster iid (event actions)
Tuxemon/Tuxemon pull request #2180
Opened 2023-12-26 21:05 UTC by JaskRendix

follows #2179 

PR updates various event actions and replaces **find_monster_by_id** with **get_monster_by_iid**, the reason is similar, `player.find_monster_by_id ` is a sort of bottleneck, the case of add_tech is the most important, I was obliged to add a last parameter called slug just to make possible to add techs to NPCs monster, now it's better (look at the map events);

2023-12-28 18:35 UTC, xirsoi requested changes
please address the comments

2023-12-28 18:35 UTC, xirsoi commented on tuxemon/event/actions/add_tech.py
> +        assert monster
Please replace this with a check that logs an error, like you did with the game_variables check on line 47

2023-12-28 18:35 UTC, xirsoi commented on tuxemon/event/actions/change_taste.py
> +        assert monster
also here

2023-12-28 18:35 UTC, xirsoi commented on tuxemon/event/actions/remove_monster.py
> +        assert monster and monster.owner
and here

2023-12-28 18:35 UTC, xirsoi commented on tuxemon/event/actions/set_monster_flair.py
> +        assert monster
and here

2023-12-28 18:35 UTC, xirsoi commented on tuxemon/event/actions/set_monster_level.py
> +            assert monster
and here

2023-12-28 18:35 UTC, xirsoi commented on tuxemon/event/actions/set_monster_plague.py
> +            assert monster
and another one

2023-12-28 18:35 UTC, xirsoi commented on tuxemon/event/actions/set_monster_status.py
> +            assert monster
you know the drill :P

2023-12-28 18:35 UTC, xirsoi commented on tuxemon/event/actions/store_monster.py
> +        assert monster and monster.owner
last one maybe?

2023-12-28 18:35 UTC, xirsoi commented on tuxemon/event/actions/trading.py
> +        assert removed.owner
similar thing here

2023-12-28 18:35 UTC, xirsoi commented on tuxemon/event/actions/trading.py
> +        assert removed.owner and added.owner
no assert!

2023-12-28 18:35 UTC, xirsoi commented on tuxemon/event/actions/trading.py
> +        assert monster_id
and another

2023-12-28 20:24 UTC, xirsoi approved these changes, later dismissed

2024-01-12 03:22 UTC, bitcraft submitted a review, later dismissed

2024-01-12 03:23 UTC, bitcraft commented
conflicts

2024-01-12 08:06 UTC, JaskRendix commented
@bitcraft fixed

2024-01-21 16:25 UTC, bitcraft approved these changes

2024-01-21 16:25 UTC, merged