get_monster_by_iid_storage (event actions)
Tuxemon/Tuxemon pull request #2182
Opened 2023-12-27 07:27 UTC by JaskRendix

split out get_monster_by_iid_storage from #2180

PR proposes to create **get_monster_by_iid_storage** to look in all the boxes (all entities in the map)

2023-12-28 18:42 UTC, xirsoi requested changes

2023-12-28 18:42 UTC, xirsoi commented on tuxemon/event/actions/withdraw_monster.py
> +        assert monster and monster.owner
assert rears it's ugly head again :P

2023-12-28 18:42 UTC, xirsoi commented on tuxemon/event/actions/spawn_monster.py
>          mother_id = uuid.UUID(trainer.game_variables["breeding_mother"])
I know you didn't change line 51, but could you get rid of that assert too while you're in here?

2024-01-21 16:26 UTC, bitcraft approved these changes

2024-01-21 16:27 UTC, merged