evolution (path)
Tuxemon/Tuxemon pull request #2184
Opened 2023-12-29 11:12 UTC by JaskRendix

when working on monster I noticed a bottleneck with evolution, we can set:

```
            "path": "standard",
            "at_level": 36,
            "monster_slug": "agnigon"
```
but it doesn't allow to add multiple parameters, like
```
            "path": "standard",
            "at_level": 36,
            "monster_slug": "agnigon"
            "variable": "season:winter"
```
for doing this above, I would be obliged to set path "variable", so I decided to remove the path and doing a multiple check on booleans
eg
```
            "at_level": 36, >true?
            "monster_slug": "agnigon" fixed parameter
            "variable": "season:winter" > true?
```
in this way we can simplify the code too in **check_evolution**

2024-01-01 15:54 UTC, Grimmys requested changes

2024-01-01 15:54 UTC, Grimmys commented on tuxemon/event/conditions/check_evolution.py
> +        return bool(evolving)
I would instead check whether the list (`evolving`) is empty or not. I feel like it would be more descriptive of what is verified here.

2024-01-04 20:16 UTC, Grimmys approved these changes

2024-01-12 03:24 UTC, bitcraft approved these changes

2024-01-12 03:24 UTC, merged