replace action-automatic-releases (build.yaml)
Tuxemon/Tuxemon pull request #2228
Opened 2024-01-21 14:03 UTC by JaskRendix

split out from #2204 (requires more testing)

PR proposes to replace **marvinpinto/action-automatic-releases@latest** with https://github.com/softprops/action-gh-release. This because marvinpinto's action isn't updated since Autumn 2022 and it still runs with node 12. Node 12 is deprecated as pointed out [here in github blog](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/)

I put:
```
          # Generate changelog from commit messages
          # generate_release_notes: true
```
because eventually we can replace the token with this or enable both

2024-01-27 10:00 UTC, JaskRendix commented
@Murmele regarding this, maybe you're using the same actions in other places too.

download-artifact has been updated to v4, but it fails here:
```
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: list artifacts folder
        run: |
          echo "Show artifacts folder:"
          ls artifacts
          echo "Show artifacts/tuxemon_windows_installer folder:"
          ls "artifacts/tuxemon_windows_installer" <------------ no issue, it founds the folder
          echo "Show artifacts/Tuxemon-x86_64:"
          ls "artifacts/Tuxemon-x86_64"  <------------ it doesn't found the folder
```

2024-01-27 15:14 UTC, Murmele commented
Hi, is the second one the linux version?

2024-01-27 15:20 UTC, JaskRendix commented
> Hi, is the second one the linux version?

@Murmele yes, it seems like the second one since it comes after.

2024-01-28 03:08 UTC, xirsoi submitted a review, later dismissed

2024-01-30 10:06 UTC, Murmele commented
> > Hi, is the second one the linux version?
> 
> @Murmele yes, it seems like the second one since it comes after.

Is there a similar folder?

2024-01-30 10:11 UTC, Murmele commented
I thought about the workflow with the flatpak manifest and I think it is better to move the manifest into the repository instead of pulling.

1) Manifest in Repository (Easily changeable, also Requirements can be changed easily, maybe with a script so they get changed whenever Requirements.txt changes)
2) The github CI gets much faster, because all those sed commands can be removed

When Publishing, just updating the Flatpak manifest in the Flathub repository. So that means in the Flathub repository there is always the stable version and in the Tuxemon repository there is always the development version.

The current workflow has some issues and is not that comfortable.

2024-01-30 11:11 UTC, JaskRendix commented
> > > Hi, is the second one the linux version?
> > 
> > 
> > @Murmele yes, it seems like the second one since it comes after.
> 
> But now in the CI it finds it?
> 
> The flatpak artifact is here: https://github.com/Tuxemon/Tuxemon/actions/runs/7686861458?pr=2228

True, but the publishing is still failing [here](https://github.com/Tuxemon/Tuxemon/actions/runs/7688299541/job/20949421643), probably because we need to change `ls artifacts` into `ls -R artifacts`

2024-01-30 11:14 UTC, JaskRendix commented
> I thought about the workflow with the flatpak manifest and I think it is better to move the manifest into the repository instead of pulling.

@Murmele I agree with you about this as well as removing the sed, but I don't understand which manifest.

2024-01-30 11:23 UTC, Murmele commented
> > I thought about the workflow with the flatpak manifest and I think it is better to move the manifest into the repository instead of pulling.
> 
> @Murmele I agree with you about this as well as removing the sed, but I don't understand which manifest.

The manifest ( instructions how to build the flapak package) is the yaml file which will be fetched from flathub repo.

2024-01-30 18:09 UTC, JaskRendix commented
@Murmele  move `org.tuxemon.Tuxemon/org.tuxemon.Tuxemon.yaml` inside the `build.yaml` or the opposite?

2024-01-30 20:37 UTC, Murmele commented
No moving the yaml file somewhere into the repository and then changing the path in the build.yml to that path

2024-01-31 20:31 UTC, JaskRendix commented
@Murmele like this?

2024-01-31 21:10 UTC, Murmele requested changes
Rename the build_flatpak.yaml to `org.tuxemon.Tuxemon.yaml`

2024-01-31 21:10 UTC, Murmele commented on buildconfig/flatpak/build_flatpak.yaml
> +      tag: v0.4.34
```suggestion
      tag: development
```

2024-01-31 21:56 UTC, JaskRendix commented
@Murmele done, but it doesn't find the file with cat

2024-02-01 14:07 UTC, Murmele requested changes

2024-02-01 14:07 UTC, Murmele commented on .github/workflows/build.yml
> +      run: cat org.tuxemon.Tuxemon.yaml
```suggestion
      run: cat buildconfig/flatpak/org.tuxemon.Tuxemon.yaml
```

2024-02-01 14:07 UTC, Murmele commented on .github/workflows/build.yml
> +        manifest-path: org.tuxemon.Tuxemon.yaml
```suggestion
        manifest-path: buildconfig/flatpak/org.tuxemon.Tuxemon.yaml
```

2024-02-01 14:07 UTC, Murmele commented on .github/workflows/build.yml
> +        manifest-path: org.tuxemon.Tuxemon.yaml
Can you try this?

2024-02-01 14:22 UTC, JaskRendix commented on .github/workflows/build.yml
> +        manifest-path: org.tuxemon.Tuxemon.yaml
@Murmele done, but same output

2024-02-01 14:24 UTC, JaskRendix commented
do we need to update this?
```
    - name: Checkout development branch
      run: |
        cd org.tuxemon.Tuxemon <<---------
        git checkout development
```

2024-02-01 15:50 UTC, Murmele commented
> do we need to update this?
> 
> ```
>     - name: Checkout development branch
>       run: |
>         cd org.tuxemon.Tuxemon <<---------
>         git checkout development
> ```

This is not needed anymore. Also the comment above can be removed.

Remove this: 
```
# Turn this on once the requirements (requirements.txt) changed and the build is not working anymore
    # Create development branch at https://github.com/flathub/org.tuxemon.Tuxemon and
    # Create development branch at https://github.com/flathub/org.tuxemon.Tuxemon and
    # update the requirements as described in the Readme. Turn it off again when the requirements in the
    # update the requirements as described in the Readme. Turn it off again when the requirements in the
    # master branch on flathub are aligned again with the Tuxemon requirements
    # master branch on flathub are aligned again with the Tuxemon requirements
    - name: Checkout development branch
    - name: Checkout development branch
      run: |
      run: |
        cd org.tuxemon.Tuxemon
        cd org.tuxemon.Tuxemon
        git checkout development
        git checkout development
```

2024-02-01 16:33 UTC, JaskRendix commented
@Murmele done

2024-02-01 17:28 UTC, Murmele commented
Can you add an 'ls' to see in which folder the ci is before the cat command?

2024-02-01 17:31 UTC, Murmele commented
- name: Checkout repository
      uses: actions/checkout@v4

This is missing before the stackoverflow comment.
Otherwise the repo is not available

2024-02-01 18:11 UTC, JaskRendix commented
@Murmele good! done! now it stops here:
```
** (flatpak-builder:187): ERROR **: 18:10:26.133: Failed to load included manifest (/__w/Tuxemon/Tuxemon/buildconfig/flatpak/portmidi.json): Failed to open file ?/__w/Tuxemon/Tuxemon/buildconfig/flatpak/portmidi.json?: No such file or directory
/usr/bin/xvfb-run: line 181:   187 Trace/breakpoint trap   (core dumped) DISPLAY=:$SERVERNUM XAUTHORITY=$AUTHFILE "$@" 2>&1
Error: Build failed: Error: The process '/usr/bin/xvfb-run' failed with exit code 133
```

2024-02-01 18:19 UTC, JaskRendix commented
@Murmele done, I have added the portmidi, libshake, etc. at the moment

2024-02-01 18:23 UTC, Murmele commented
> @Murmele done, I have added the portmidi, libshake, etc. at the moment

Great. Can you add also the readme and the scripts from there? So that everything is together

2024-02-01 18:27 UTC, JaskRendix commented
@Murmele everything is added

2024-02-01 18:30 UTC, Murmele commented
Great work 🙂

2024-02-17 23:55 UTC, bitcraft approved these changes

2024-02-17 23:55 UTC, merged

2024-02-18 10:50 UTC, JaskRendix commented
@Murmele  the PR has been merged, but it doesn't publish:
```
tuxemon-installer.exe
Show artifacts/tuxemon_windows_installer folder:
artifacts/tuxemon_windows_installer:
tuxemon-installer.exe
Show artifacts/Tuxemon-x86_64:
ls: cannot access 'artifacts/Tuxemon-x86_64': No such file or directory
Error: Process completed with exit code 2.
```
this is the piece of code:
```
      - name: list artifacts folder
        run: |
          echo "Show artifacts folder:"
          ls -R artifacts
          echo "Show artifacts/tuxemon_windows_installer folder:"
          ls -R "artifacts/tuxemon_windows_installer"
          echo "Show artifacts/Tuxemon-x86_64:"
          ls -R "artifacts/Tuxemon-x86_64"
```
what could be the issue? because windows installer is fine, but tuxemon-86 no. Do we need to put **ls -R artifacts** again?

2024-02-19 07:35 UTC, Murmele commented
@JaskRendix the list artifacts folder was just to check if the folders exist, this is not required. For some reason it does not find the Bundle.

I checked a few pullrequest actions: https://github.com/Tuxemon/Tuxemon/actions/runs/7947846121
There the flatpak package is available. Next step is to find out why it will not be found by this part: https://github.com/Tuxemon/Tuxemon/blob/development/.github/workflows/build.yml#L177-L187

Do you have a link where you found this error message?

2024-02-19 12:25 UTC, JaskRendix commented
@Murmele sure, here: https://github.com/Tuxemon/Tuxemon/actions/runs/7945212993/job/21691724375

2024-02-19 15:01 UTC, Murmele commented
Hmm looking into the flatpak build:
```
Uploaded /__w/Tuxemon/Tuxemon/Tuxemon.flatpak (99.8%) bytes 201326592:209715199
Uploaded /__w/Tuxemon/Tuxemon/Tuxemon.flatpak (100.0%) bytes 209715200:209970981
Total size of all the files uploaded is 209970982 bytes
File upload process has finished. Finalizing the artifact upload
Artifact has been finalized. All files have been successfully uploaded!

The raw size of all the files that were specified for upload is 209977872 bytes
The size of all the files that were uploaded is 209970982 bytes. This takes into account any gzip compression used to reduce the upload size, time and storage
```

```
Show artifacts folder:
artifacts:  <--- No Tuxemon-x86_64 is listed. But also any other name is not listed
tuxemon_windows_installer

artifacts/tuxemon_windows_installer:
tuxemon-installer.exe
Show artifacts/tuxemon_windows_installer folder:
artifacts/tuxemon_windows_installer:
tuxemon-installer.exe
Show artifacts/Tuxemon-x86_64:
ls: cannot access 'artifacts/Tuxemon-x86_64': No such file or directory
```

2024-02-19 15:43 UTC, JaskRendix commented
@Murmele  I think the issue is here:
```
      - name: list artifacts folder
        run: |
          echo "Show artifacts folder:"
          ls -R artifacts
          echo "Show artifacts/tuxemon_windows_installer folder:"
          ls -R "artifacts/tuxemon_windows_installer"
          echo "Show artifacts/Tuxemon-x86_64:"
          ls -R "artifacts/Tuxemon-x86_64"   <-------------
```
because I think if we switch the names
```
          echo "Show artifacts/Tuxemon-x86_64:"
          ls -R "artifacts/Tuxemon-x86_64"
          echo "Show artifacts/tuxemon_windows_installer folder:"
          ls -R "artifacts/tuxemon_windows_installer"
```
we would have the same issue with windows, it's like the ls -R is unable to find it

2024-02-19 15:45 UTC, Murmele commented
> artifacts

But why` ls -R artifacts` does not list anything?