regionproperties + collision zone
Tuxemon/Tuxemon pull request #2247
Opened 2024-02-04 15:33 UTC by JaskRendix

PR fixes wrong behavior of collision zone.

let's say there is a tree and the truck is set as enter_from and exit_from = up, left and right

right now, this doesn't work, because when walking the collision zone is overwritten.

The PR removes the overwriting.

eg. here it checks if there is a preexistent collision zone, then it updates only the specific field (entity).
```
        if region:
            prop = RegionProperties(
                region.enter_from,
                region.exit_from,
                region.endure,
                self,
                region.key,
            )
        else:
            prop = RegionProperties(
                enter_from=[], exit_from=[], endure=[], entity=self, key=None
            )
```

2024-02-07 11:23 UTC, Grimmys requested changes

2024-02-07 11:23 UTC, Grimmys commented on tuxemon/states/world/worldstate.py
> +            else:
No need for this else, since nothing is done inside.

2024-02-18 00:02 UTC, bitcraft commented
@Grimmys do the changes look good to you now?

2024-02-18 12:59 UTC, adrienave approved these changes

2024-02-18 13:06 UTC, Grimmys approved these changes

2024-02-20 20:12 UTC, bitcraft approved these changes

2024-02-20 20:12 UTC, merged