777 leaf777 patch 1
Tuxemon/Tuxemon pull request #851
Opened 2021-03-06 17:17 UTC by 777Leaf777

Fixed the Floating points aad changed the map encoding. might need to delete the Tabba_town.tmx and replace mine with ZhongTiaos more up to date version.

2021-03-08 12:18 UTC, bitcraft requested changes

2021-03-08 12:18 UTC, bitcraft commented on Azure_Town.tmx
> +    <property name="act10" value="dialog  Town Hall"/>
Use translated_dialog unless it cannot be used for some reason.

2021-03-08 12:18 UTC, bitcraft commented on mods/tuxemon/maps/professor_lab.tmx
> +    <property name="act20" value="dialog you picked RockKitten"/>
FYI, this is Rockitten, not RockKitten
https://wiki.tuxemon.org/index.php?title=Rockitten

2021-03-08 12:18 UTC, bitcraft commented on mods/tuxemon/maps/taba_town.tmx
> -<?xml version="1.0" encoding="UTF-8"?>
why is taba_town deleted?

2021-03-08 12:18 UTC, bitcraft commented on mods/tuxemon/maps/timber_town.tmx
> +  <object id="190" x="404.801" y="388.55"/>
float

2021-03-08 12:18 UTC, bitcraft commented on mods/tuxemon/maps/timber_town.tmx
> +  <object id="120" type="collision" x="0" y="608" width="447.202" height="32"/>
float

2021-03-08 12:18 UTC, bitcraft commented on mods/tuxemon/maps/witcher_route_7.tmx
> +  <object id="14" type="collision" x="-7.47922" y="227.424" width="36.2881" height="252.078"/>
float

2021-03-08 12:18 UTC, bitcraft commented on mods/tuxemon/maps/witcher_route_7.tmx
> +  <object id="47" x="41.8283" y="234.025" height="0.277008"/>
float

2021-03-08 12:18 UTC, bitcraft commented on timber_town.tmx
> +  <object id="190" x="404.801" y="388.55"/>
float

2021-03-08 12:18 UTC, bitcraft commented on witcher_route_7.tmx
> +  <object id="23" type="collision" x="160" y="0" width="36.0111" height="123.269"/>
float

2021-03-08 12:18 UTC, bitcraft commented on mods/tuxemon/maps/Azure_Town.tmx
> +    <property name="act10" value="dialog  Town Hall"/>
use translated dialog

2022-02-23 14:32 UTC, xirsoi commented
Closing due to abandonment

2022-02-23 14:32 UTC, closed without merging