Next step in the story
Tuxemon/Tuxemon pull request #856
Opened 2021-03-20 23:59 UTC by Qiangong2

Added more to the story.

1. Obtain Tuxemon
2. Have first battle
3. Allie arrests the Tuxemon Professor

2021-03-21 18:09 UTC, xirsoi requested changes
Other than the Professor clones, this looks good to me!

2021-03-21 18:09 UTC, xirsoi commented on mods/tuxemon/db/npc/professor-cardiling.json
> +    "slug": "professor-cardiling",
We shouldn't do it this way.
Merge develop and use the new functionality for add_monster.

2021-03-31 21:40 UTC, xirsoi approved these changes

2021-04-05 20:20 UTC, bitcraft approved these changes
thanks for the update

2021-04-05 20:21 UTC, merged